[workspace]
members = ["packages/*", "contracts/*"]
resolver = "1"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
calc-rs = { path = "packages/calc-rs" }
cosmwasm-schema = "2.2.0"
cosmwasm-std = { version = "2.2.2", features = ["cosmwasm_2_1"] }
cosmwasm-storage = "1.5.2"
cw-multi-test = "2.0.0"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
cw2 = "2.0.0"
rand = "0.9.1"
rujira-rs = { git = "https://gitlab.com/thorchain/rujira.git", rev = "bde18fdb02b9b0213e43308c7ebf5b865886ac97" }
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.58" }
